spring:
  application:
    name: ticketverse

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketverse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Use flyway for schema migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    com.ticketverse: DEBUG
    org.springframework.security: DEBUG
